### ISSUE TITLE
Explore Durable Functions/Entities

### ISSUE THREAD

**Issue by anthturner** [microsoft/AuthJanitor#1]
It is on my short list to replace IDataStore<T> with Entity Framework. As part of this endeavor, I'm wondering whether switching the Functions app to use Durable Entities might be a good idea, as most of the bulk of the Functions code is around CRUD operations, and less around actual orchestration. Using Durable Entities might *vastly* simplify maintaining the administrator interface.

https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp

**Comment by peterbryntesson** [comment]
Just noting here that we now have an implementation of IDataStore for Entity Framework Core

**Comment by anthturner** [comment]
Because of how the services are now separate from the hosting approach, this isn't likely to work out, so I'm closing it.
